/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { passagesSearch } from "../../funcs/passagesSearch.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.SearchPassagesRequest$inboundSchema,
};

export const tool$passagesSearch: ToolDefinition<typeof args> = {
  name: "passages_search",
  description: `Search Bible passages

Returns search results for Bible passages based on the provided query`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await passagesSearch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
