/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { passagesGetAudio } from "../../funcs/passagesGetAudio.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetPassageAudioRequest$inboundSchema,
};

export const tool$passagesGetAudio: ToolDefinition<typeof args> = {
  name: "passages_get-audio",
  description: `Get Bible passage audio

Returns audio file for Bible passages based on the provided query`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await passagesGetAudio(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
