/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { passagesGetText } from "../../funcs/passagesGetText.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetPassageTextRequest$inboundSchema,
};

export const tool$passagesGetText: ToolDefinition<typeof args> = {
  name: "passages-get-text",
  description: `Get Bible passage text

Returns Bible passage text based on the provided query parameters`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await passagesGetText(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
