/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { passagesGetHtml } from "../../funcs/passagesGetHtml.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetPassageHtmlRequest$inboundSchema,
};

export const tool$passagesGetHtml: ToolDefinition<typeof args> = {
  name: "passages_get-html",
  description: `Get Bible passage HTML

Returns Bible passage text with HTML formatting`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await passagesGetHtml(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
