/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { passagesGetHtml } from "../funcs/passagesGetHtml.js";
import { passagesGetText } from "../funcs/passagesGetText.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Passages extends ClientSDK {
  /**
   * Get Bible passage HTML
   *
   * @remarks
   * Returns Bible passage text with HTML formatting
   */
  async getHtml(
    request: operations.GetPassageHtmlRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPassageHtmlResponseBody> {
    return unwrapAsync(passagesGetHtml(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Bible passage text
   *
   * @remarks
   * Returns Bible passage text based on the provided query parameters
   */
  async getText(
    request: operations.GetPassageTextRequest,
    options?: RequestOptions,
  ): Promise<operations.GetPassageTextResponseBody> {
    return unwrapAsync(passagesGetText(
      this,
      request,
      options,
    ));
  }
}
