/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { passagesGetHtml } from "../funcs/passagesGetHtml.js";
import { passagesGetText } from "../funcs/passagesGetText.js";
import { passagesSearch } from "../funcs/passagesSearch.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Passages extends ClientSDK {
  /**
   * Search Bible passages
   *
   * @remarks
   * Returns search results for Bible passages based on the provided query
   *
   * @see {@link https://api.esv.org/docs/passage-search/} - Esv.org API Docs for `/v3/passage/search`
   */
  async search(
    request: operations.SearchPassagesRequest,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.SearchPassagesResponse, { page: number }>
  > {
    return unwrapResultIterator(passagesSearch(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Bible passage HTML
   *
   * @remarks
   * Returns Bible passage text with HTML formatting
   *
   * @see {@link https://api.esv.org/docs/passage-html/} - Esv.org API Docs for `/v3/passages/html`
   */
  async getHtml(
    request: operations.GetPassageHtmlRequest,
    options?: RequestOptions,
  ): Promise<components.PassageResponse> {
    return unwrapAsync(passagesGetHtml(
      this,
      request,
      options,
    ));
  }

  /**
   * Get Bible passage text
   *
   * @remarks
   * Returns Bible passage text based on the provided query parameters
   *
   * @see {@link https://api.esv.org/docs/passage-text/} - Esv.org API Docs for `/v3/passages/text`
   */
  async getText(
    request: operations.GetPassageTextRequest,
    options?: RequestOptions,
  ): Promise<components.PassageResponse> {
    return unwrapAsync(passagesGetText(
      this,
      request,
      options,
    ));
  }
}
