// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"io"
	"mockserver/internal/sdk/models/components"
)

type GetPassageAudioRequest struct {
	// Bible passage reference (e.g., "John 3:16" or "43011016")
	Query string `queryParam:"style=form,explode=true,name=q"`
}

func (o *GetPassageAudioRequest) GetQuery() string {
	if o == nil {
		return ""
	}
	return o.Query
}

type GetPassageAudioResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
}

func (o *GetPassageAudioResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetPassageAudioResponse) GetResponseStream() io.ReadCloser {
	if o == nil {
		return nil
	}
	return o.ResponseStream
}
