/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Example usage of the esv-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx passagesGetHtml.ts
 */

import { Esv } from "esv-sdk";

const esv = new Esv({
  apiKey: process.env["ESV_API_KEY"] ?? "",
});

async function main() {
  const result = await esv.getHtml({
    query: "John 1:1",
  });

  console.log(result);
}

main().catch(console.error);
