workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    ESV.org API:
        inputs:
            - location: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/walker/esv/esv-org-api
targets:
    esv:
        target: typescript
        source: ESV.org API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/walker/esv/esv-org-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
