// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type PassageMeta struct {
	Canonical    *string `json:"canonical,omitempty"`
	ChapterStart []int64 `json:"chapter_start,omitempty"`
	ChapterEnd   []int64 `json:"chapter_end,omitempty"`
	PrevVerse    *int64  `json:"prev_verse,omitempty"`
	NextVerse    *int64  `json:"next_verse,omitempty"`
	PrevChapter  []int64 `json:"prev_chapter,omitempty"`
	NextChapter  []int64 `json:"next_chapter,omitempty"`
}

func (o *PassageMeta) GetCanonical() *string {
	if o == nil {
		return nil
	}
	return o.Canonical
}

func (o *PassageMeta) GetChapterStart() []int64 {
	if o == nil {
		return nil
	}
	return o.ChapterStart
}

func (o *PassageMeta) GetChapterEnd() []int64 {
	if o == nil {
		return nil
	}
	return o.ChapterEnd
}

func (o *PassageMeta) GetPrevVerse() *int64 {
	if o == nil {
		return nil
	}
	return o.PrevVerse
}

func (o *PassageMeta) GetNextVerse() *int64 {
	if o == nil {
		return nil
	}
	return o.NextVerse
}

func (o *PassageMeta) GetPrevChapter() []int64 {
	if o == nil {
		return nil
	}
	return o.PrevChapter
}

func (o *PassageMeta) GetNextChapter() []int64 {
	if o == nil {
		return nil
	}
	return o.NextChapter
}
